### ISSUE TITLE
Request: reference node:latest instead of node:carbon

### ISSUE THREAD

**Issue by srchulo** [cronobo/node-chrome-headless-puppeteer#1]
I'm not sure if there's a reason carbon is used instead of latest, but carbon is on node 8 vs 11.13. Would it be possible to switch to node:latest instead? If not, I could just fork this.

**Comment by Overdrivr** [comment]
Hi, we stuck to carbon because our build process is frozen with that version.
Probably best to do a fork for now, we won't touch this in a near future

**Comment by srchulo** [comment]
Sounds good. Thanks for the response!

**Comment by srchulo** [comment]
Thanks again. Just for reference for anyone who stumbles here, I did end up forking this using node:latest:

https://github.com/srchulo/node-latest-chrome-headless-puppeteer
https://hub.docker.com/r/srchulo/node-latest-chrome-headless-puppeteer
